name: vcpkg

on: [push, pull_request]

jobs:
  job:
    name: ${{ matrix.platform }}-${{ github.workflow }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-14-intel, macos-14-arm, windows-2022]
        include:
          - platform: macos-14-intel
            runner: 'macos-14-large'
            triplet: 'x64-osx-14'
          - platform: macos-14-arm
            runner: 'macos-14-xlarge'
            triplet: 'arm64-osx-14'
          - platform: windows-2022
            runner: 'windows-2022-xl8'
            triplet: 'x64-windows'
    env:
      VCPKG_INSTALLED_DIR: '${{ github.workspace }}/vcpkg_installed/${{ matrix.platform }}'
      VCPKG_DEFAULT_TRIPLET: '${{ matrix.triplet }}'
      VCPKG_DEFAULT_HOST_TRIPLET: '${{ matrix.triplet }}'
      VCPKG_OVERLAY_TRIPLETS: '${{ github.workspace }}/overlay/triplets'
    steps:
      - name: Setup XCode
        if: runner.os == 'macOS'
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Install missing dependencies
        run:   |
               if [ "$RUNNER_OS" == "macOS" ]; then
                    brew install autoconf-archive automake libtool md4c
               fi
        shell: bash
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          submodules: 'recursive'
      - name: Update cmake
        uses: lukka/get-cmake@latest
      - name: Run vcpkg
        if: runner.os != 'Windows'
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: 'vcpkg.json'
          runVcpkgInstall: true
      - name: Run vcpkg
        if: runner.os == 'Windows'
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: 'c:\vcpkg'
          vcpkgJsonGlob: 'vcpkg.json'
          runVcpkgInstall: true
      - name: Compress packages
        run: |
          tar -czpf '${{ github.workspace }}/${{ matrix.platform }}.tar.gz' -C '${{ github.workspace }}/vcpkg_installed' '${{ matrix.platform }}'
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: 'packages-${{ matrix.platform }}'
          path: '${{ github.workspace }}/${{ matrix.platform }}.tar.gz'
